//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelesteAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CelesteAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing lambdas to ILCursor.EmitDelegate..
        /// </summary>
        internal static string CL0001Description {
            get {
                return ResourceManager.GetString("CL0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing lambdas to ILCursor.EmitDelegate, as it emits inefficient code. Pass a reference (method group) to a static method instead..
        /// </summary>
        internal static string CL0001MessageFormat {
            get {
                return ResourceManager.GetString("CL0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda passed to ILCursor.EmitDelegate.
        /// </summary>
        internal static string CL0001Title {
            get {
                return ResourceManager.GetString("CL0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing instance methods to ILCursor.EmitDelegate..
        /// </summary>
        internal static string CL0002Description {
            get {
                return ResourceManager.GetString("CL0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing instance methods to ILCursor.EmitDelegate, as it can result in capturing an instance of your class in unexpected ways.
        /// </summary>
        internal static string CL0002MessageFormat {
            get {
                return ResourceManager.GetString("CL0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance method passed to EmitDelegate.
        /// </summary>
        internal static string CL0002Title {
            get {
                return ResourceManager.GetString("CL0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call &apos;orig&apos; in hooks..
        /// </summary>
        internal static string CL0003Description {
            get {
                return ResourceManager.GetString("CL0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one code path should call &apos;orig&apos; in hooks, to allow other hooks to run properly.
        /// </summary>
        internal static string CL0003MessageFormat {
            get {
                return ResourceManager.GetString("CL0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orig not called in hook.
        /// </summary>
        internal static string CL0003Title {
            get {
                return ResourceManager.GetString("CL0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make method static.
        /// </summary>
        internal static string CL0004CodeFixTitle {
            get {
                return ResourceManager.GetString("CL0004CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooks should be static..
        /// </summary>
        internal static string CL0004Description {
            get {
                return ResourceManager.GetString("CL0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooks should be static, otherwise it can result in capturing an instance of your class in unexpected ways.
        /// </summary>
        internal static string CL0004MessageFormat {
            get {
                return ResourceManager.GetString("CL0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-static Hook.
        /// </summary>
        internal static string CL0004Title {
            get {
                return ResourceManager.GetString("CL0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILCursor.Remove or RemoveRange should never be used..
        /// </summary>
        internal static string CL0005Description {
            get {
                return ResourceManager.GetString("CL0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t call ILCursor.Remove or RemoveRange, as it can break other IL hooks which search for the removed instructions.
        /// </summary>
        internal static string CL0005MessageFormat {
            get {
                return ResourceManager.GetString("CL0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILCursor.Remove or RemoveRange used.
        /// </summary>
        internal static string CL0005Title {
            get {
                return ResourceManager.GetString("CL0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing multiple predicates to ILCursor.(Try)Goto*..
        /// </summary>
        internal static string CL0006Description {
            get {
                return ResourceManager.GetString("CL0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing several predicates to ILCursor.(Try)Goto* methods, as other hooks might inject instructions between the target instructions. If possible, split them into separate calls instead..
        /// </summary>
        internal static string CL0006MessageFormat {
            get {
                return ResourceManager.GetString("CL0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple predicates to ILCursor.(Try)Goto*.
        /// </summary>
        internal static string CL0006Title {
            get {
                return ResourceManager.GetString("CL0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid ctor for Entity marked with the CustomEntity attribute..
        /// </summary>
        internal static string CL0007Description {
            get {
                return ResourceManager.GetString("CL0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities marked with the CustomEntity attribute must have one of the following constructors: 
        ///            {0}(EntityData, Vector2 offset, EntityID),
        ///            {0}(EntityData, Vector2 offset),
        ///            {0}(Vector2 offset),
        ///            {0}().
        /// </summary>
        internal static string CL0007MessageFormat {
            get {
                return ResourceManager.GetString("CL0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid ctor for CustomEntity.
        /// </summary>
        internal static string CL0007Title {
            get {
                return ResourceManager.GetString("CL0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class marked by CustomEntity doesn&apos;t extend Entity..
        /// </summary>
        internal static string CL0008Description {
            get {
                return ResourceManager.GetString("CL0008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes marked with the CustomEntity attribute must extend from Entity.
        /// </summary>
        internal static string CL0008MessageFormat {
            get {
                return ResourceManager.GetString("CL0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class marked by CustomEntity doesn&apos;t extend Entity.
        /// </summary>
        internal static string CL0008Title {
            get {
                return ResourceManager.GetString("CL0008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity Generator method missing..
        /// </summary>
        internal static string CL0009Description {
            get {
                return ResourceManager.GetString("CL0009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomEntity attribute specifies a generator method &apos;{0}&apos;, but it is missing from the class.
        /// </summary>
        internal static string CL0009MessageFormat {
            get {
                return ResourceManager.GetString("CL0009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity generator method missing.
        /// </summary>
        internal static string CL0009Title {
            get {
                return ResourceManager.GetString("CL0009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity generator method has invalid parameters..
        /// </summary>
        internal static string CL0010Description {
            get {
                return ResourceManager.GetString("CL0010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters for CustomEntity generator method. They must be one of the following:
        ///            {0}(Level, LevelData, EntityData, Vector2 offset, EntityID),
        ///            {0}(EntityData, Vector2 offset, EntityID),
        ///            {0}(EntityData, Vector2 offset),
        ///            {0}(Vector2 offset),
        ///            {0}().
        /// </summary>
        internal static string CL0010MessageFormat {
            get {
                return ResourceManager.GetString("CL0010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity generator method parameters invalid.
        /// </summary>
        internal static string CL0010Title {
            get {
                return ResourceManager.GetString("CL0010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity generator method is invalid..
        /// </summary>
        internal static string CL0011Description {
            get {
                return ResourceManager.GetString("CL0011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity generator methods must be static, and return Entity or a type extending Entity.
        /// </summary>
        internal static string CL0011MessageFormat {
            get {
                return ResourceManager.GetString("CL0011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity generator method invalid.
        /// </summary>
        internal static string CL0011Title {
            get {
                return ResourceManager.GetString("CL0011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity with no IDs..
        /// </summary>
        internal static string CL0012Description {
            get {
                return ResourceManager.GetString("CL0012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity attributes need at least one IDs passed as an argument to function properly.
        /// </summary>
        internal static string CL0012MessageFormat {
            get {
                return ResourceManager.GetString("CL0012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomEntity with no IDs.
        /// </summary>
        internal static string CL0012Title {
            get {
                return ResourceManager.GetString("CL0012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.Scene accessed in ctor..
        /// </summary>
        internal static string CL0013Description {
            get {
                return ResourceManager.GetString("CL0013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.Scene is always null in the constructor. Move any code that requires the Scene to Added (called before all entities are added to the scene) or Awake (called after all entities are added).
        /// </summary>
        internal static string CL0013MessageFormat {
            get {
                return ResourceManager.GetString("CL0013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.Scene accessed in ctor.
        /// </summary>
        internal static string CL0013Title {
            get {
                return ResourceManager.GetString("CL0013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Tracker if possible..
        /// </summary>
        internal static string CL0014Description {
            get {
                return ResourceManager.GetString("CL0014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of EntityList.Find(All), use Scene.Tracker with types marked with the [Tracked] attribute for much better performance. EntityList.Find(All) loops through all entities in the scene, the Tracker is a Dictionary lookup..
        /// </summary>
        internal static string CL0014MessageFormat {
            get {
                return ResourceManager.GetString("CL0014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Tracker if possible.
        /// </summary>
        internal static string CL0014Title {
            get {
                return ResourceManager.GetString("CL0014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker used on untracked type..
        /// </summary>
        internal static string CL0015Description {
            get {
                return ResourceManager.GetString("CL0015Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to call Tracker methods on types not marked with [Tracked] or [TrackedAs] will fail at runtime. Add the [Tracked] or [TrackedAs] attribute to {0} if possible..
        /// </summary>
        internal static string CL0015MessageFormat {
            get {
                return ResourceManager.GetString("CL0015MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker used on untracked type.
        /// </summary>
        internal static string CL0015Title {
            get {
                return ResourceManager.GetString("CL0015Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TrackedAs usage..
        /// </summary>
        internal static string CL0016Description {
            get {
                return ResourceManager.GetString("CL0016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using [TrackedAs(typeof({0}))] when your class does not extend {0} can fail at runtime, due to code outside your control expecting Tracker methods to only return types extending {0}..
        /// </summary>
        internal static string CL0016MessageFormat {
            get {
                return ResourceManager.GetString("CL0016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TrackedAs usage.
        /// </summary>
        internal static string CL0016Title {
            get {
                return ResourceManager.GetString("CL0016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid yield return orig(...)..
        /// </summary>
        internal static string CL0017Description {
            get {
                return ResourceManager.GetString("CL0017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using `yield return orig(...)`, as it introduces a 1-frame delay. Use `yield return new SwapImmediately(orig(...))`, or, if this method is used by a StateMachine, enumerate the enumerator manually and yield return all of its elements in a loop..
        /// </summary>
        internal static string CL0017MessageFormat {
            get {
                return ResourceManager.GetString("CL0017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid yield return orig(...).
        /// </summary>
        internal static string CL0017Title {
            get {
                return ResourceManager.GetString("CL0017Title", resourceCulture);
            }
        }
    }
}
