//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelesteAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CelesteAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing lambdas to ILCursor.EmitDelegate..
        /// </summary>
        internal static string CL0001Description {
            get {
                return ResourceManager.GetString("CL0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing lambdas to ILCursor.EmitDelegate, as it emits inefficient code. Pass a reference (method group) to a static method instead..
        /// </summary>
        internal static string CL0001MessageFormat {
            get {
                return ResourceManager.GetString("CL0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda passed to ILCursor.EmitDelegate.
        /// </summary>
        internal static string CL0001Title {
            get {
                return ResourceManager.GetString("CL0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing instance methods to ILCursor.EmitDelegate..
        /// </summary>
        internal static string CL0002Description {
            get {
                return ResourceManager.GetString("CL0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid passing instance methods to ILCursor.EmitDelegate, as it can result in capturing an instance of your class in unexpected ways.
        /// </summary>
        internal static string CL0002MessageFormat {
            get {
                return ResourceManager.GetString("CL0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance method passed to EmitDelegate.
        /// </summary>
        internal static string CL0002Title {
            get {
                return ResourceManager.GetString("CL0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call &apos;orig&apos; in hooks..
        /// </summary>
        internal static string CL0003Description {
            get {
                return ResourceManager.GetString("CL0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one code path should call &apos;orig&apos; in hooks, to allow other hooks to run properly.
        /// </summary>
        internal static string CL0003MessageFormat {
            get {
                return ResourceManager.GetString("CL0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orig not called in hook.
        /// </summary>
        internal static string CL0003Title {
            get {
                return ResourceManager.GetString("CL0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make method static.
        /// </summary>
        internal static string CL0004CodeFixTitle {
            get {
                return ResourceManager.GetString("CL0004CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooks should be static..
        /// </summary>
        internal static string CL0004Description {
            get {
                return ResourceManager.GetString("CL0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooks should be static, otherwise it can result in capturing an instance of your class in unexpected ways.
        /// </summary>
        internal static string CL0004MessageFormat {
            get {
                return ResourceManager.GetString("CL0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-static Hook.
        /// </summary>
        internal static string CL0004Title {
            get {
                return ResourceManager.GetString("CL0004Title", resourceCulture);
            }
        }
    }
}
